steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/erudite-harbor-414918/ev-rest-api-nestjs:$COMMIT_SHA',
        '.',
      ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/erudite-harbor-414918/ev-rest-api-nestjs:$COMMIT_SHA']

  # Deploy the image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ev-rest-api-nestjs'
      - '--image'
      - 'gcr.io/erudite-harbor-414918/ev-rest-api-nestjs:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/erudite-harbor-414918/ev-rest-api-nestjs:$COMMIT_SHA'
